### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\csaki\AtomBackups'

### ISSUE THREAD

**Issue by csakis** [dbenson24/config-import-export#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [config-import-export](https://github.com/dbenson24/config-import-export) package, v0.3.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\csaki\AtomBackups'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir 'C:\Users\csaki\AtomBackups'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
    at ImportView.module.exports.ImportView.attach (file:///C:/Users/csaki/.atom/packages/config-import-export/lib/config-import-view.coffee:40:16)
    at atom-workspace.commandSubscription.atom.commands.add.config-import-export:import (file:///C:/Users/csaki/.atom/packages/config-import-export/lib/config-import-view.coffee:19:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\csaki\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\csaki\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\csaki\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\csaki\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -3:43.5.0 settings-view:open (atom-text-editor.editor.is-focused)
  5x -3:37 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:35.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -3:35.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.0 config-import-export:import (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "config-import-export": {
    "defaultPath": {
      "win32": "C:\\Users\\csaki\\AtomBackups",
      "darwin": "",
      "linux": "",
      "freebsd": "",
      "sunos": ""
    }
  }
}
```
### Installed Packages

``` coffee
# User
config-import-export, v0.3.1
Handlebars, v1.2.1
language-spacebars, v0.2.2
seti-icons, v0.4.5
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by dbenson24** [comment]
Did you make an Atom backups folder there?

**Comment by csakis** [comment]
Creating my backup folder fixed it.
