### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/home/walr/AtomBackups'

### ISSUE THREAD

**Issue by WilfredLemus** [dbenson24/config-import-export#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [config-import-export](https://github.com/dbenson24/config-import-export) package, v0.3.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/home/walr/AtomBackups'

```
At fs.js:856

Error: ENOENT: no such file or directory, scandir '/home/walr/AtomBackups'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at ImportView.module.exports.ImportView.attach (/home/walr/.atom/packages/config-import-export/lib/config-import-view.coffee:40:16)
    at atom-workspace.commandSubscription.atom.commands.add.config-import-export:import (/home/walr/.atom/packages/config-import-export/lib/config-import-view.coffee:19:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -9:11.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -9:04.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -9:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 config-import-export:import (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "config-import-export": {
    "defaultPath": {
      "darwin": "",
      "freebsd": "",
      "linux": "/home/walr/AtomBackups",
      "sunos": "",
      "win32": ""
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.8
atom-django, v0.3.2
config-import-export, v0.3.1
django-templates, v0.5.0
emmet, v2.4.3
highlight-selected, v0.11.2
minimap, v4.24.6
minimap-highlight-selected, v4.4.0
python-autopep8, v0.1.3
seti-icons, v1.3.1

# Dev
No dev packages
```

**Comment by WilfredLemus** [comment]
solution
create directory AtomBackups
mkdir /to/root/AtomBackups
