### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/Sachdev/AtomBackups'

### ISSUE THREAD

**Issue by cksachdev** [dbenson24/config-import-export#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [config-import-export](https://github.com/dbenson24/config-import-export) package, v0.3.1
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/Sachdev/AtomBackups'

```
At fs.js:856

Error: ENOENT: no such file or directory, scandir '/Users/Sachdev/AtomBackups'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at ImportView.module.exports.ImportView.attach (/Users/Sachdev/.atom/packages/config-import-export/lib/config-import-view.coffee:40:16)
    at atom-workspace.commandSubscription.atom.commands.add.config-import-export:import (/Users/Sachdev/.atom/packages/config-import-export/lib/config-import-view.coffee:19:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -4:34.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:26.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:08.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:07.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:01.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:01.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:59.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 config-import-export:import (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "config-import-export": {
    "defaultPath": {
      "darwin": "/Users/Sachdev/AtomBackups",
      "freebsd": "",
      "linux": "",
      "sunos": "",
      "win32": ""
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
config-import-export, v0.3.1
file-icons, v1.7.15
fonts, v1.5.0

# Dev
No dev packages
```

**Comment by DungeonCaster** [comment]
This is the third time this error has been reported here (see closed issues). For each of the previous two issues the solution was to manually create the missing directory. The question needs to be asked why is this a repeatedly reported error? Is there a problem with the directory being automatically created or a problem with the documentation requiring the user to create the directory manually?

**Comment by filipjonckers** [comment]
The package should ask for an import / export directory instead of "assuming" a hardcoded directory.  This would also enable users to select a folder in Google Drive, OneDrive, Dropbox, network drive or an usb drive
This would greatly improve the user friendliness.
