### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/michaelcalkins/AtomBackups'

### ISSUE THREAD

**Issue by SammieEtje** [dbenson24/config-import-export#4]
The module refers to a user-folder that does not exist on my computer:

fs.js:856
Hide Stack Trace
Error: ENOENT: no such file or directory, scandir '/Users/michaelcalkins/AtomBackups'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:496:28)
    at ImportView.module.exports.ImportView.attach (/Users/sander/.atom/packages/config-import-export/lib/config-import-view.coffee:40:16)
    at atom-workspace.commandSubscription.atom.commands.add.config-import-export:import (/Users/sander/.atom/packages/config-import-export/lib/config-import-view.coffee:19:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1127:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:341:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

**Comment by jas32096** [comment]
you just have to make the folder or change it in the preferences
