### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '~/AtomBackups'

### ISSUE THREAD

**Issue by fgomes3** [dbenson24/config-import-export#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [config-import-export](https://github.com/dbenson24/config-import-export) package 0.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'C:\Users\FabioGomes\AtomBackups'

```
At fs.js:951

Error: ENOENT: no such file or directory, scandir 'C:\Users\FabioGomes\AtomBackups'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at ImportView.module.exports.ImportView.attach (/packages/config-import-export/lib/config-import-view.coffee:40:16)
    at /packages/config-import-export/lib/config-import-view.coffee:19:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -6:50.9.0 window:toggle-menu-bar (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:33.6.0 window:toggle-dev-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -6:08.8.0 application:add-project-folder (atom-pane.pane.active)
     -4:53 core:confirm (input.hidden-input)
     -3:42.3.0 core:backspace (input.hidden-input)
     -3:41.1.0 core:confirm (input.hidden-input)
  2x -2:55.8.0 core:backspace (input.hidden-input)
     -2:54.4.0 core:confirm (input.hidden-input)
     -2:26.2.0 core:delete (input.hidden-input)
     -0:13 config-import-export:import (input.hidden-input)
```

### Non-Core Packages

```
config-import-export 0.3.1 
```

**Comment by jwoodrow99** [comment]
If you look at the settings for this package in your editor, take a look at what the default path for your system, and make sure it is pointing to the directory that contains the JSON config file, or where you want it to be exported to.
