### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir ''

### ISSUE THREAD

**Issue by t1gu1** [dbenson24/config-import-export#7]
[Enter steps to reproduce:]

Platform: Linux/Ubuntu

1. simply import

Also the first time, the folder AtomBackups was not created.
I think it needs a sudo it'll fix some things i think.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [config-import-export](https://github.com/dbenson24/config-import-export) package 0.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir ''

```
At fs.js:951

Error: ENOENT: no such file or directory, scandir ''
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at ImportView.module.exports.ImportView.attach (/packages/config-import-export/lib/config-import-view.coffee:40:16)
    at /packages/config-import-export/lib/config-import-view.coffee:19:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:41 config-import-export:import (input.hidden-input)
     -3:25.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.4.0 config-import-export:import (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
angular-2-typeScript-snippets 0.6.3 
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.18 
atom-terminal-panel 4.4.4 
atom-typescript 11.0.1 
busy-signal 1.4.1 
close-tags 0.6.0 
config-import-export 0.3.1 
expose 0.14.0 
file-icons 2.1.4 
Hydrogen 1.12.1 
intentions 1.1.2 
language-mongodb 0.3.1 
language-pug 0.0.21 
linter 2.1.4 
linter-csslint 1.3.4 
linter-json-lint 0.1.1 
linter-php 1.3.2 
linter-pug-lint 0.2.0 
linter-sass-lint 1.7.4 
linter-tslint 1.3.0 
linter-ui-default 1.2.3 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
platformio-ide-terminal 2.5.0 
qolor 0.4.1 
rest-client 1.3.1 
turbo-javascript 1.4.0 
typescript-modules-helper 0.8.0 
```

**Comment by zumbalogy** [comment]
This package seems somewhat abandoned, but in case it helps future users: Having a backup file in the AtomBackups made this error go away for me.
